name: build

on:
  push:
    tags:
      - 'release-v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/strengthening/goghostex

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
        env:
          GOPATH: /home/runner/work/goghostex/go

      - name: Check the program norm
        run: go vet -composites=false ./...
        env:
          GOPATH: /home/runner/work/goghostex/go

      - name: Build
        run: go build -v ./...
        env:
          GOPATH: /home/runner/work/goghostex/go

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/strengthening/goghostex

      - name: Login the Docker service
        uses: azure/docker-login@v1
        with:
          login-server: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTER_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTER_DOCKER_PASSWORD }}

      - name: Ready to release, and update the gobuild lastest image
        run: |
          cd /home/runner/work/goghostex/go/src/github.com/strengthening/goghostex
          docker build --rm -t registry.cn-hongkong.aliyuncs.com/strengthening/goghostex .
          docker push registry.cn-hongkong.aliyuncs.com/strengthening/goghostex

  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: strengthening/docker
          event-type: gobuild
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
